//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBG.ORM.EF.SQLServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Super100网管系统自监控v1Entities : DbContext
    {
        public Super100网管系统自监控v1Entities()
            : base("name=Super100网管系统自监控v1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_YJCollectProgramMonitor_Alm> T_YJCollectProgramMonitor_Alm { get; set; }
        public virtual DbSet<T_YJCollectProgramMonitor_AssistJob> T_YJCollectProgramMonitor_AssistJob { get; set; }
        public virtual DbSet<T_YJCollectProgramMonitor_BaseData> T_YJCollectProgramMonitor_BaseData { get; set; }
        public virtual DbSet<T_YJCollectProgramMonitor_Cron> T_YJCollectProgramMonitor_Cron { get; set; }
        public virtual DbSet<T_YJCollectProgramMonitor_TrLog> T_YJCollectProgramMonitor_TrLog { get; set; }
        public virtual DbSet<V_YJCollectProgramMonitor_AlmView> V_YJCollectProgramMonitor_AlmView { get; set; }
        public virtual DbSet<V_YJCollectProgramMonitor_BaseDataView> V_YJCollectProgramMonitor_BaseDataView { get; set; }
    }
}
