//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBG.ORM.EF.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_YJCollectProgramMonitor_AssistJob
    {
        public System.Guid JobId { get; set; }
        public string JobCron { get; set; }
        public string JobCls { get; set; }
        public Nullable<bool> IsStart { get; set; }
        public string JobRemark { get; set; }
    }
}
