//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBG.ORM.EF.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_YJCollectProgramMonitor_Alm
    {
        public System.Guid AlarmId { get; set; }
        public System.Guid FK_BaseData { get; set; }
        public string AlmTitle { get; set; }
        public string AlmInfo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> PutMQStatus { get; set; }
        public string AlmState { get; set; }
        public string LogFileName { get; set; }
        public Nullable<System.DateTime> InputDt { get; set; }
        public Nullable<System.DateTime> LastModifyDt { get; set; }
    
        public virtual T_YJCollectProgramMonitor_BaseData T_YJCollectProgramMonitor_BaseData { get; set; }
    }
}
