//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBG.ORM.EF.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_YJCollectProgramMonitor_Cron
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_YJCollectProgramMonitor_Cron()
        {
            this.T_YJCollectProgramMonitor_BaseData = new HashSet<T_YJCollectProgramMonitor_BaseData>();
        }
    
        public System.Guid CronId { get; set; }
        public string Cron { get; set; }
        public string CronRemark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_YJCollectProgramMonitor_BaseData> T_YJCollectProgramMonitor_BaseData { get; set; }
    }
}
