//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBG.ORM.EF.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_YJCollectProgramMonitor_TrLog
    {
        public System.Guid TrLogId { get; set; }
        public Nullable<System.DateTime> InputDt { get; set; }
        public string TrTbl { get; set; }
        public string TrTyp { get; set; }
    }
}
