//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBG.ORM.EF.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_YJCollectProgramMonitor_AlmView
    {
        public System.Guid AlarmId { get; set; }
        public System.Guid FK_BaseData { get; set; }
        public string AlmTitle { get; set; }
        public string AlmInfo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> PutMQStatus { get; set; }
        public string AlmState { get; set; }
        public string LogFileName { get; set; }
        public Nullable<System.DateTime> InputDt { get; set; }
        public Nullable<System.DateTime> LastModifyDt { get; set; }
        public Nullable<System.Guid> BaseDataId { get; set; }
        public string MonitorObjIp { get; set; }
        public string MonitorObjLogPath { get; set; }
        public string EvtTyp { get; set; }
        public string AlmLvl { get; set; }
        public string MonitorObjName { get; set; }
        public Nullable<bool> IsNeedChk { get; set; }
        public Nullable<System.Guid> FK_Cron { get; set; }
        public string BaseDataRemark { get; set; }
        public string MonitorPrefixUri { get; set; }
        public Nullable<System.Guid> CronId { get; set; }
        public string Cron { get; set; }
        public string CronRemark { get; set; }
    }
}
