//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : 多数据库统一接口
//  @ File Name : 适配器模式.cs
//  @ Date : 2017/6/9
//  @ Author : 
//
//


using System.Configuration;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SQLite;

namespace HBG.Data
{
    /// <summary>
    /// 数据库交互统一接口，可扩展支付多种数据库，如SQL Server、SQLite、Oracle等
    /// </summary>
    public abstract class DbAccessor
    {
        public abstract DataSet ExecuteDataSet(string cmdText);
        public abstract DbDataReader ExecuteReader(string cmdText);
        public abstract object ExecuteScalar(string cmdText);
        public abstract int ExecuteNonQuery(string cmdText);
    }
}
 




