using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace HBG.Utils.OpenXml
{
    public static class Convert
    {
        /// <summary>
        /// 输入英文字母字符得到相应的数字(ASCII编码)
        /// </summary>
        /// <param name="ch"></param>
        /// <returns></returns>
        public static int GetLetterCharCode(char ch)
        {
            switch (ch)
            {
                case 'A':
                    return 65;
                case 'B':
                    return 66;
                case 'C':
                    return 67;
                case 'D':
                    return 68;
                case 'E':
                    return 69;
                case 'F':
                    return 70;
                case 'G':
                    return 71;
                case 'H':
                    return 72;
                case 'I':
                    return 73;
                case 'J':
                    return 74;
                case 'K':
                    return 75;
                case 'L':
                    return 76;
                case 'M':
                    return 77;
                case 'N':
                    return 78;
                case 'O':
                    return 79;
                case 'P':
                    return 80;
                case 'Q':
                    return 81;
                case 'R':
                    return 82;
                case 'S':
                    return 83;
                case 'T':
                    return 84;
                case 'U':
                    return 85;
                case 'V':
                    return 86;
                case 'W':
                    return 87;
                case 'X':
                    return 88;
                case 'Y':
                    return 89;
                case 'Z':
                    return 90;

                case 'a':
                    return 97;
                case 'b':
                    return 98;
                case 'c':
                    return 99;
                case 'd':
                    return 100;
                case 'e':
                    return 101;
                case 'f':
                    return 102;
                case 'g':
                    return 103;
                case 'h':
                    return 104;
                case 'i':
                    return 105;
                case 'j':
                    return 106;
                case 'k':
                    return 107;
                case 'l':
                    return 108;
                case 'm':
                    return 109;
                case 'n':
                    return 110;
                case 'o':
                    return 111;
                case 'p':
                    return 112;
                case 'q':
                    return 113;
                case 'r':
                    return 114;
                case 's':
                    return 115;
                case 't':
                    return 116;
                case 'u':
                    return 117;
                case 'v':
                    return 118;
                case 'w':
                    return 119;
                case 'x':
                    return 120;
                case 'y':
                    return 121;
                case 'z':
                    return 122;
            }
            return -1;
        }
        /// <summary>
        /// 输入数字(ASCII编码)得到相应的英文字母字符
        /// </summary>
        /// <param name="ch"></param>
        /// <returns></returns>
        public static char GetLetterChar(uint code)
        {
            switch (code)
            {
                case 65:
                    return 'A';
                case 66:
                    return 'B';
                case 67:
                    return 'C';
                case 68:
                    return 'D';
                case 69:
                    return 'E';
                case 70:
                    return 'F';
                case 71:
                    return 'G';
                case 72:
                    return 'H';
                case 73:
                    return 'I';
                case 74:
                    return 'J';
                case 75:
                    return 'K';
                case 76:
                    return 'L';
                case 77:
                    return 'M';
                case 78:
                    return 'N';
                case 79:
                    return 'O';
                case 80:
                    return 'P';
                case 81:
                    return 'Q';
                case 82:
                    return 'R';
                case 83:
                    return 'S';
                case 84:
                    return 'T';
                case 85:
                    return 'U';
                case 86:
                    return 'V';
                case 87:
                    return 'W';
                case 88:
                    return 'X';
                case 89:
                    return 'Y';
                case 90:
                    return 'Z';

                case 97:
                    return 'a';
                case 98:
                    return 'b';
                case 99:
                    return 'c';
                case 100:
                    return 'd';
                case 101:
                    return 'e';
                case 102:
                    return 'f';
                case 103:
                    return 'g';
                case 104:
                    return 'h';
                case 105:
                    return 'i';
                case 106:
                    return 'j';
                case 107:
                    return 'k';
                case 108:
                    return 'l';
                case 109:
                    return 'm';
                case 110:
                    return 'n';
                case 111:
                    return 'o';
                case 112:
                    return 'p';
                case 113:
                    return 'q';
                case 114:
                    return 'r';
                case 115:
                    return 's';
                case 116:
                    return 't';
                case 117:
                    return 'u';
                case 118:
                    return 'v';
                case 119:
                    return 'w';
                case 120:
                    return 'x';
                case 121:
                    return 'y';
                case 122:
                    return 'z';
            }
            return '1';
        }

        /// <summary>
        /// 输入数字(ASCII编码)得到相应的英文字母字符
        /// </summary>
        /// <param name="ch"></param>
        /// <returns></returns>
        public static string GetLetterString(uint code)
        {
            switch (code)
            {
                case 101:
                    return "A";
                case 102:
                    return "B";
                case 103:
                    return "C";
                case 104:
                    return "D";
                case 105:
                    return "E";
                case 106:
                    return "F";
                case 107:
                    return "G";
                case 108:
                    return "H";
                case 109:
                    return "I";
                case 110:
                    return "J";
                case 111:
                    return "K";
                case 112:
                    return "L";
                case 113:
                    return "M";
                case 114:
                    return "N";
                case 115:
                    return "O";
                case 116:
                    return "P";
                case 117:
                    return "Q";
                case 118:
                    return "R";
                case 119:
                    return "S";
                case 120:
                    return "T";
                case 121:
                    return "U";
                case 122:
                    return "V";
                case 123:
                    return "W";
                case 124:
                    return "X";
                case 125:
                    return "Y";
                case 126:
                    return "Z";
                case 127:
                    return "AA";
                case 128:
                    return "AB";
                case 129:
                    return "AC";
                case 130:
                    return "AD";
                case 131:
                    return "AE";
                case 132:
                    return "AF";
                case 133:
                    return "AG";
                case 134:
                    return "AH";
                case 135:
                    return "AI";
                case 136:
                    return "AJ";
                case 137:
                    return "AK";
                case 138:
                    return "AL";
                case 139:
                    return "AM";
                case 140:
                    return "AN";
                case 141:
                    return "AO";
                case 142:
                    return "AP";
                case 143:
                    return "AQ";
                case 144:
                    return "AR";
                case 145:
                    return "AS";
                case 146:
                    return "AT";
                case 147:
                    return "AU";
                case 148:
                    return "AV";
                case 149:
                    return "AW";
                case 150:
                    return "AX";
                case 151:
                    return "AY";
                case 152:
                    return "AZ";
            }
            return "1";
        }
    }
}
