//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBG.ORM.EF.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StudentCourseView
    {
        public string RelateId { get; set; }
        public string FK_StudentId { get; set; }
        public string FK_CourseId { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string Name_1 { get; set; }
    }
}
